# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98c2e9694634ad478e5e8a4ec54f8e7acb5d489eef8b8464daf7e9f65a45870bcc4b617b7280ab8920ed8eaf98d4d308e22aa72ce0df0a6d96d9dab198f8a4b4

test:
  secret_key_base: f8fd46626a37a94655e2f1d20c44725c2941e5a6033fa5d74463a65e4bae3322242ff153a22920ade8c8525efade63622a3e26da5ce36dd067f8819b02a39ccd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
